### PR TITLE
Add support for auto-assigned client port (udpPort=0)

### PR DESCRIPTION
**Pull request by fambon**

### CODE REVIEW

**Comment by changtengfei** [comment]
@fambon Could you explain a little bit more for this PR? Is there any problem using 5000 port?

**Comment by fambon** [comment]
There is no "problem" using port 5000, as long as you have a single client running on your machine.  If you run 2 clients, the second one says "port already in use".  Same thing if some other app already uses port 5000.

One way of handling these situations is to use an auto-assigned port (specifying port 0 causes the system to allocate a non-used port for you).

**Comment by changtengfei** [comment]
@fambon I see. I have a question, how can I know which port the user is using if the port is assigned automatically?

**Comment by fambon** [comment]
Stale project. Closing.

**Pull request closed without merging**
