### PR TITLE
COAP-32 add maxRetransmit number as a parameter that can be specified

### PR DESCRIPTION
**Pull request by Heriam**
Hi @changtengfei I made a little change so that maxRetransmit can be also be tuned at need through CoAP client in code.

### CODE REVIEW

**Comment by changtengfei** [comment]
@Heriam thanks for the code! Is there a coap application you are going to modify this parameter?

**Comment by Heriam** [comment]
@changtengfei , actually it is again SW-232, with default values we would need to wait at least 20*6 = 120s to report an error of no connection which is too long. We already have the ackTimeout value of coap client tuned to 2 in OV code resulting a max waiting period of 12s with 6 tries for coap request. However I suppose 6s with 3 tries would be enough to test connection status, so that we don't need to wait too long to see the error reported every time if any problem. If this makes sense I would also send a new pull request for SW-232 accordingly.

**Comment by changtengfei** [comment]
@Heriam thanks for clarifying! I have merged SW-232 into openwsn. So this code will work with the code SW-232, which is in develop branch now? You needn't send a new PR, I just try to figure out how the code will effect the current behaviors.

**Comment by Heriam** [comment]
@changtengfei please kindly refer to here maybe :) https://github.com/Heriam/openwsn-sw/commit/42bc80e03dbf8c074cc37f1eeaca0cb5ea1a141a

**Comment by changtengfei** [comment]
@Heriam Image there is a large scale of network running, the ACK may require longer time to send back. I would not suggest to reduce the ackTimeout value. 
Also I saw your code, be aware that the coap is not only used for remote connection but also for other coap application running on mote. The coap connection between computer and mote is not that robust like the connection between computer and rPi.

**Pull request merged**
